name: patch

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
       - '**'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt -y install git

    - name: Clone slstatus
      run: |
        git clone https://git.suckless.org/slstatus

    - name: Generate patch
      run: |
        cd slstatus
        git remote add -f b https://github.com/wojciechmadry/slstatus.git
        git remote update
        git diff master remotes/b/master > wojciechmadry.patch
        git remote rm b

    - uses: actions/upload-artifact@v4
      with:
        name: wojciechmadry.patch
        path: slstatus/wojciechmadry.patch
